### ISSUE TITLE
systemd log file

### ISSUE THREAD

**Issue by DaveBlooman** [hashicorp/envconsul#116]
I am trying to run envconsul with a Go binary via systemd.  I am having issues when outputting to a log file in the following way.  I am seeing an `status=2/INVALIDARGUMENT` error.  Is there any guidance on how to run this sort of setup?

``` sh
[Unit]
Description=Foo service

[Service]
ExecStart=/bin/sh -c "/usr/bin/envconsul -consul 127.0.0.1:8500 -sanitize -upcase -prefix service/ /opt/app/gobin >>/var/log/app.log"
User=user
Group=user
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by sethvargo** [comment]
I don't use systemd, so I really have no idea. Do you have any more log output or debug information?

**Comment by DaveBlooman** [comment]
It appears that the syntax was wrong, though this only does STDOUT.

```sh
ExecStart=/bin/sh -c "exec /usr/bin/envconsul -consul 127.0.0.1:8500 -sanitize -upcase -prefix service/ /opt/app/gobin 2>> /var/log/app.log"
```

**Comment by sethvargo** [comment]
I think you want `&> /var/log/app.log`

But I think systemd does autologging of stdout and stderr for you

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. I hope the issue is fixed! If not, please open a new ticket with more detail. Thanks!

**Comment by neurostream** [comment]
I always have to re-remember how to do use envconsul with systemd, and this github issue is always the top google search for ("envconsul" AND "systemd"). 

I typically start a custom process in systemd via with a startup script instead of the final/direct executable file.  The startup script launches another sub-shell (sh'bang line).  Sometimes my startup script calls yet another startup script - which in turn might call yet another that spawns other subprocesses.  Tomcat, which I'll use in the example below, does this before finally executing java.  This requires that the systemd ExecStart item is allowed to **fork**.  The default Service unit type is "simple" - which expects to be executing the final executable directly.

Different sub shells can also have different stdin/stderr redirections. 

For this reason, I use _Type=forking_ . Hope this helps someone else:

`[Unit]
Description=tomcat
After=syslog.target network.target syslog.target consul.service

[Service]
Type=forking
LimitNOFILE=65536

EnvironmentFile=/etc/sysconfig/java.conf
EnvironmentFile=/etc/sysconfig/tomcat.conf
ExecStart=/usr/local/bin/envconsul -upcase -sanitize -prefix config -once ${CATALINA_HOME}/bin/startup.sh
ExecStop=/usr/local/bin/envconsul -upcase -sanitize -prefix config -once ${CATALINA_HOME}/bin/shutdown.sh

Restart=on-failure
RestartSec=10
Restart=always

User=service
Group=service
UMask=0007

[Install]
WantedBy=multi-user.target
`
