### ISSUE TITLE
Problems running in an Alpine container

### ISSUE THREAD

**Issue by justingood** [hashicorp/envconsul#147]
### Envconsul version
0.7.0

### Configuration
I'm using the following Dockerfile to test:
```
FROM alpine:3.6

RUN apk --no-cache add curl tar && \
    curl -L "https://releases.hashicorp.com/envconsul/0.7.0/envconsul_0.7.0_linux_amd64.tgz" | tar zxf - -C /bin/

CMD ["/bin/envconsul", "--version"]
```

### Command
Running the container results in Docker reporting a strange error:
```shell
$ docker build -t envconsul-test .
$ docker run -it envconsul-test
standard_init_linux.go:178: exec user process caused "no such file or directory"
```

The file does exist, however. This can be verified by hopping into the container by running: `docker run -it envconsul sh`
```
/ # /bin/envconsul
sh: /bin/envconsul: not found
/ # ls -l /bin/envconsul
-rwxr-xr-x    1 501      dialout    7314688 Aug  2 02:56 /bin/envconsul
```

Testing that same Dockerfile with the previous version of Envconsul (0.6.2) appears to work without problems. Out of curiosity, I tested the latest Consul-Template (0.19.0) which also works fine.

Has the build process for the official release changed with this new version of Envconsul?

**Comment by sethvargo** [comment]
Hi @justingood 

Thank you for opening an issue. I think there are a few things here. First, we publish an official container now (hashicorp/envconsul). There's an alpine and scratch version - you can see the Dockerfiles in this repo.

Second, you should _never_ use `-L` on the releases service. We will never redirect you. If you get a redirect, that's probably a bad sign.

Third, the build process changed, and this is definitely a bug:

```
root@dd21177a432c:/# ldd envconsul-0.6
	not a dynamic executable
root@dd21177a432c:/# ldd envconsul-0.7
	linux-vdso.so.1 =>  (0x00007fff2e59e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f932e855000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f932e48b000)
	/lib64/ld-linux-x86-64.so.2 (0x00005600b7829000)
```

As you can see, the new build is dynamically linked, even though it's explicitly disabled. I'm still investigating this. It's failing on alpine because that link doesn't exist (but I'm not sure why Go is trying to do DLL anyway).

**Comment by justingood** [comment]
Thanks @sethvargo !

For what it's worth, the official container does work correctly for me. Am I right to assume this is because this one was built _inside_ Alpine to begin with, therefore avoiding this dynamic linking bug?

Good point about the redirects, I'll amend them. Thanks for flagging that!

**Comment by sethvargo** [comment]
@justingood it's because I forgot an underscore 😦
