### ISSUE TITLE
envconsul shell variable interpolation differences between 0.6 and 0.7

### ISSUE THREAD

**Issue by kakoni** [hashicorp/envconsul#180]
### Environment
Consul agent with
```consul kv put redis/config/connections 5```

### command
```shell
envconsul -log-level info -prefix redis/config /bin/bash -c 'echo $connections'
```

### output with 0.6.2
```
2018/10/09 11:51:15 [INFO] (runner) running
2018/10/09 11:51:15 [INFO] (runner) running command /bin/bash -c echo $connections
5
2018/10/09 11:51:15 [INFO] (runner) running
```

### output with 0.7.3
```
2018/10/09 11:54:14.036873 [INFO] (runner) running
2018/10/09 11:54:14.036992 [INFO] (child) spawning: /bin/bash -c echo 

2018/10/09 11:54:14.039337 [INFO] (runner) running
```

**Comment by ffleming** [comment]
I'm a big +1 on this! I've been writing a lot of wrapper scripts as a workaround, but the reintroduction of the 0.6.x behavior would be great for us.

**Comment by eikenb** [comment]
From 0.6 to 0.7 the code was changed to use github.com/mattn/go-shellwords to parse the exec'd command. The parser supports parsing shell variables in the command and is set to do so...
https://github.com/hashicorp/envconsul/blob/40f672f1729eedd97e4c25bd4455c43713ed5bb2/runner.go#L307
It evaluates the env variables (eg. $connections above) in the environment running the envconsul command itself, without the consul supplied values being injected into it. They are injected into an environment that is passed to the child command...
https://github.com/hashicorp/envconsul/blob/40f672f1729eedd97e4c25bd4455c43713ed5bb2/runner.go#L301-L304

I think the fix is to just not have the shellwords parser parse the environment variables, just have it ignore them. Ie. commenting out that `parseEnv = true` line seems to fix it. I'm going to wait till Monday to submit the PR with the fix.

**Comment by eikenb** [comment]
Eg. with that line commented out...

```
[~]consul kv put foo/port 80
Success! Data written to: foo/port
[~]envconsul -log-level info -prefix foo -exec '/bin/sh -c "echo $port"'
2019/05/12 01:48:11.832345 [INFO]  v0.7.3 ()
2019/05/12 01:48:11.832359 [INFO] (runner) creating new runner (once: false)
2019/05/12 01:48:11.832629 [INFO] (runner) creating watcher
2019/05/12 01:48:11.832743 [INFO] (runner) starting
2019/05/12 01:48:11.834345 [INFO] (runner) running
2019/05/12 01:48:11.834502 [INFO] (child) spawning: /bin/sh -c echo $port
80
2019/05/12 01:48:11.835306 [INFO] (runner) running
2019/05/12 01:48:11.835330 [INFO] (runner) environment was the same
2019/05/12 01:48:11.835338 [INFO] (cli) subprocess exited
2019/05/12 01:48:11.835341 [INFO] (runner) stopping
2019/05/12 01:48:11.835370 [INFO] (child) stopping process
```
