### ISSUE TITLE
0.7.4 binary not released for KV2 support

### ISSUE THREAD

**Issue by grantdlr** [hashicorp/envconsul#193]
Last release is almost a year old and need to update pipelines to support KV2.  please compile and release binary

**Comment by eedwards-sk** [comment]
Is this project still being maintained?

I have a use case that is perfect for `envconsul`, but it's been a year since a release and there are multiple PRs that look unreviewed.

**Comment by jefferai** [comment]
Envconsul is in a bit of a weird place because it not only works with Consul now but also with Vault, and on top of that the original maintainer of it at HashiCorp is no longer with us. We definitely have plans to get things going with it again, we've just been working on the long term vision for it and which team will be responsible for maintenance.

**Comment by eedwards-sk** [comment]
@jefferai I'm sad to see Seth Vargo go! 😢 

I saw a similar comment on another issue a few months back, so any sort of update on timeline, when available, would be appreciated.

"Long term vision" sounds a little ominous 👻, but we do have "short term" improvements that are awaiting acceptance, so even having someone spike on reviewing what's there would be greatly appreciated.

envconsul / consul-template, at least to me, perfectly closes the gap between consul/vault and application config. Although, I noticed there's a decent amount of overlapping behavior between the two tools, so maybe combining them into one tool would be simpler to maintain? I can foresee use cases for needing to provide env vars AND a config file, which is a little weird to do by chaining the tools together.

**Comment by jefferai** [comment]
I wouldn't say "ominous" but it's things like exactly what you mentioned -- do consul-template and envconsul really need to be separate binaries? Their config is extremely similar, the ways they behave and the functions they perform are for the most part also extremely similar. So by long-term vision I mean things like, "can we not only do some dev on it but see if we can actually make the UX way nicer and make the maintenance burden simpler at the same time".

As for spiking reviewing PRs, there is currently an effort to find a provisional maintainer within the company, I think it's one of those "nobody that's here currently really knows the code base so it's not an insignificant amount of effort to understand it well enough to feel good about merging PRs, so we probably need to dedicate someone's time" things. And another impedement is that we are growing rapidly, so ramping them up on the main projects takes a lot of time from the existing engineers.

I'm giving you the inside info because we like to be transparent around here, but to be clear: we're committed to envconsul because it enables our users. Apologies it's taking a while to get someone cycled up on it, but it's not because we don't care about it, promise :-)

**Comment by grantdlr** [comment]
Would you have a rough ETA?  even down to a year quarter would be nice

**Comment by myspotontheweb** [comment]
The alternative tool to envconsul, [vaultenv](https://github.com/channable/vaultenv) also cannot currently support  [KV version 2](https://github.com/channable/vaultenv/issues/62), yet.

So disappointed I enabled this :-(

**Comment by james-lawrence** [comment]
I'd be happen to spike a vaultenv tool and maintain it if people here are interested in contributing.

**Comment by eedwards-sk** [comment]
After abandoning envconsul and finding a way to get similar behavior from consul-template, I believe hashicorp should just scuttle envconsul and we should centralize around consul-template. It could easily be extended to set env vars instead of rendering a template. Two separate tools no longer makes sense.

**Comment by james-lawrence** [comment]
I'm indifferent, but hashicorp doesn't seem to have the bandwidth atm. and this is actively a blocker for me personally and consul template seems far more work to setup and use than the 100 or so lines of code to convert a set of vault keys to an environment file would be.

**Comment by eedwards-sk** [comment]
@james-lawrence consul-template shares the majority of the library that envconsul does, except that envconsul is missing numerous features which were copy+pasted from consul-template and never implemented

my suggestion is to contribute to consul-template to add envconsul-like support (e.g. allow it to set env vars) rather than fork off this project, which is already incomplete

hope that makes sense!

**Comment by james-lawrence** [comment]
i wasn't going to fork was just going to write the code. my initial impressions of consul-template seems like far more ops work than writing the code directly solve my (and apparently others) issue. I need a scriptable CLI tool, not a daemon.

**Comment by eedwards-sk** [comment]
@james-lawrence They're much more similar than you might think. envconsul is also a daemon, so I'm not sure what you mean there, and consul-template can be ran "one off".

Either way, my point (which is purely to help you avoid wasted work, so take it or leave it) is that you'll probably find that consul-template is a shorter path to a feature-complete envconsul than just iterating on envconsul itself.

**Comment by jefferai** [comment]
Ideally they will be combined into one at some point. As James suggested it's a bandwidth problem but one we are trying to solve.

**Comment by davewongillies** [comment]
Not to be that guy, but I'm going to be that guy and say that more bandwidth has been spent discussing this issue than it would've take to just quickly cut a point release of something that we want and already exists in the master branch.

We're not asking for a new feature or code to be written, we just want a release cut.

**Comment by james-lawrence** [comment]
@davewongillies depends who is doing the discussion, I don't suspect anyone from hashicorp in this conversation is capable of actually cutting a release.

**Comment by tyd** [comment]
I put some builds up here: https://github.com/tyd/envconsul/releases/tag/v0.7.4a

**Includes:**
- Support Vault KV2 when there are multiple keys in a secret #192
- Allow users to use ENV vars in prefix paths using Go templates #167

The Kv2 support implemented in #186 (and 0.7.4) was pretty much broken because it didn't support multiple secrets in a path/secret.

**Comment by eikenb** [comment]
Given the discussion here I thought this seemed like a good place to note that I recently took a position at Hashicorp and my first task is to adopt envconsul and consul-template. I'm just starting so please be patient as I familiarize myself with the code, review the issues and PRs in both projects. But know that someone will be working on these projects going forward. Thanks.

**Comment by hakamadare** [comment]
@eikenb that's great news, really happy to hear it :)

**Comment by james-lawrence** [comment]
for those who want a kv solution now. https://github.com/james-lawrence/vaultenv works for my usecase, which is simple converting key/values of secrets to an environment file format.

**Comment by grantdlr** [comment]
That is brilliant news... first class citizen again :)

**Comment by eikenb** [comment]
Has anyone looked at and/or used either #192 or #206? Any preferences between the 2 implementations?

**Comment by daveadams** [comment]
Yep @eikenb we can build from master, but ideally we'd like to see a release with the v2 support baked in that we can just fetch from releases.hashicorp.com into our internal packaging workflow.

**Comment by eikenb** [comment]
Hey @daveadams. My previous (edited) comment was initially based on the idea that KV2 support wasn't in master yet, that one of those PRs I referenced were needed. But that wasn't the case and so I was just saying that I could build it from master, as is, and address this ticket.

I'm working on a new release now. You can track the progress in the [Milestones](https://github.com/hashicorp/envconsul/milestones). It is almost ready.

**Comment by eikenb** [comment]
What's the feelings on merging #211 before the 8.0 release? @tyd requested it be merged and I'm considering it but wanted to see if people wanted a release with the current code first. It doesn't seem like it'd break compatibility with the current code in master, but I thought ask and give people a chance to chime in. Thanks.

**Comment by eikenb** [comment]
Just pushed 8.0. Binaries at https://releases.hashicorp.com/envconsul/0.8.0/

**Comment by grantdlr** [comment]
GOLD!!!  Thankyou
