### ISSUE TITLE
v0.11.0 was not published to Dockerhub

### ISSUE THREAD

**Issue by abaehreMC** [hashicorp/envconsul#258]
The most recent version of env-consul on dockerhub (https://hub.docker.com/r/hashicorp/envconsul) is 0.10.0-scratch which was pushed 9 months ago. 

Since v0.11.0 came out in November it might be nice to have that available especially since that allows for the usage of the "vault_agent_token_file" field.

**Comment by eikenb** [comment]
Hey @abaehreMC, thanks for reporting this. We've just revamped our release process and I'm not sure the old one will even work anymore... I'm planning on reviewing outstanding PRs and issues and doing a release soon-ish (I'm doing this for consul-template first).  That new release process has all the docker image building stuff integrated to it, so that release will have updated docker images.

To get to it.. Can this wait until I get that release out or do you need it ASAP?

**Comment by abaehreMC** [comment]
We're not in a huge rush, but it would be a nice QoL kind of thing. Appreciate you reaching out.

**Comment by AnthonyLaiuppa** [comment]
Hiya, we would also benefit well from this container image. Is there any update on when we can look for this next release?

**Comment by abaehreMC** [comment]
Can I bump this?

**Comment by eikenb** [comment]
Hey @AnthonyLaiuppa, @abaehreMC.

I'm finishing up a consul-esm release right now but envconsul is in the queue for some attention soon after. A docker image is definitely going to be part of that.

**Comment by MPV** [comment]
No new docker images yet (but something tells me they’ll be available shortly)? 😊 https://hub.docker.com/r/hashicorp/envconsul/tags
