### ISSUE TITLE
0.12.0 causes substantial increase in audit log entries on Vault server

### ISSUE THREAD

**Issue by noahtrilling** [hashicorp/envconsul#272]
After updating to envconsul 0.12.0, we saw a substantial increase in audit log entries on our Vault server instance, which nearly filled up the disk and caused an outage. After rolling back to version 0.11.0, the disk utilization issue went away immediately. No other meaningful changes were made to our code besides the envconsul version update. Updating to envconsul 0.12.0 produced this same result in multiple different applications. Can you please investigate what could have caused such a massive influx in the number of requests being made by envconsul to the Vault server between 0.11.0 and 0.12.0?

**Comment by eikenb** [comment]
Hey @noahtrilling, thanks for the report and sorry to hear about that.

I've reproduced the issue and have narrowed it down to the consul-template dependency update. Rebuilding envconsul with the same dependency version as 0.11.0, consul-template 0.25.1, fixes the issue (though not how I want). I'll keep digging.

**Comment by eikenb** [comment]
Found the problem. Consul-template grew an option to set the default lease duration for vault and it didn't do it in a backwards compatible way. So the default inherited by this app was 0.

Note that I consider this an issue with using consul-template as a library, which it isn't designed for, rather than a bug with consul-template not maintaining compatibility. These sorts of issues should hopefully go away as we migrate to the [new library](https://github.com/hashicorp/hcat) that is replacing consul-template's use as such.

**Comment by eikenb** [comment]
PR to fix the issue has been pushed. Once merged I'll probably do a 0.12.1 release to get this out. Thanks again for reporting.

**Comment by noahtrilling** [comment]
Thanks for the prompt work to get this fixed!
