### ISSUE TITLE
Be able to forward multiple signals to child processes

### ISSUE THREAD

**Issue by greggilbert** [hashicorp/envconsul#63]
It'd be great to have envconsul be able to pass multiple signals to its child processes. Example: I'm using envconsul with Sneakers. With Sneakers, you can send the parent process [five different signals](https://github.com/jondot/sneakers/blob/60a5461f4e0f71b490b6170248bdd29f52839b4c/lib/sneakers/cli.rb#L78-L83) based on what you want to do (i.e. stop, restart, reconfigure). Being able to have the envconsul process pass any of those through would be really helpful.

**Comment by sethvargo** [comment]
@greggilbert do you want to be able to send multiple signals or just any one of the signals? Envconsul already has the ability to customize the signal with the `-kill-signal` flag or configuration option.

**Comment by greggilbert** [comment]
More the latter; being able to send any one of them. In other words, not being locked into just using the `kill-signal` one.

**Comment by sethvargo** [comment]
@greggilbert how would envconsul know which one to send?

**Comment by greggilbert** [comment]
Maybe it could have a whitelist of signals and pass any through that it finds? I'm thinking something similar to `trap` in bash.

**Comment by sethvargo** [comment]
Hey @greggilbert 

I'm still not following. You want to send all the signals to the process at the same time? I understand the desire to customize the flag, but I must admit I still don't understand the desire to send multiple signals to the subprocess. I especially don't know what you mean by "any through that it finds". Envconsul will send whatever signal you give it, regardless of whether the child responds. There's no way for envconsul to intelligently know what signals a subprocess responds to.

**Comment by greggilbert** [comment]
Sorry, I lost track of this. I think you may have already answered my question: "Envconsul will send whatever signal you give it, regardless of whether the child responds." 

In my case, the child process responds to a number of different signals - SIGINT, SIGTERM, etc. My understanding based on the envconsul docs was that _only_ the `kill-signal` would get passed through to the child process, and that the others would be filtered out and not forwarded on. So in my case, if I specify SIGTERM as the kill-signal, then SIGINT wouldn't be forwarded to the child process. But based on what you said before, is that incorrect? Do all signals get passed on to the child process?

**Comment by sethvargo** [comment]
@greggilbert I am still really having trouble following your question. I am sorry. Let me try to clarify differently.

When you specify a value for the kill-signal, that is the signal sent to the process when values in Consul change. Envconsul does not know what signals the process responds to.

**Comment by greggilbert** [comment]
Ha, I'm sorry we're not on the same level. I get that envconsul doesn't know what signals the process responds to; that's not a concern.

Suppose I specify the kill-signal as SIGINT. What happens if I send SIGTERM to the envconsul process?

**Comment by ryanuber** [comment]
I think the disconnect here is that envconsul isn't a signal proxy in any way. The `kill-signal` option is a signal which is sent to the child whenever envconsul exits, or receives new data for the environment. It is intended to alert the child that it should exit.

In your case, if you want to send a signal to the sneakers process, you can send it directly to the PID of sneakers, instead of through envconsul. A pidfile for the sneakers process could help you achieve that. You would probably want to set the `kill-signal` to SIGTERM, judging by [this line](https://github.com/jondot/sneakers/blob/60a5461f4e0f71b490b6170248bdd29f52839b4c/lib/sneakers/cli.rb#L78).

Does that make sense?

**Comment by greggilbert** [comment]
Thanks, @ryanuber, that does make sense. So the tldr here is that only the `kill-signal` signal will get proxied down, and everything else doesn't. So in the Sneakers case, sending SIGTERM to envconsul would stop the child processes.

So my original question was if it would be possible to proxy more than one signal down to the children. Based on your response, it sounds like the better solution would be to find the child process directly and send the message there. Sneakers provides signals for both stopping and restarting. Suppose I want to use Sneakers' restart every time envconsul detects a change, but also be able to kill the child process via envconsul. That would require that two signals be able to be proxied down. Is that possible?

Apologies on this going so long. Consul and envconsul are really fantastic, and I appreciate you guys taking the time and effort here!

**Comment by ryanuber** [comment]
@greggilbert this currently isn't possible, as envconsul replaces the child process when changes are detected.

There are two related issues open for this:
* #54 suggests adding the ability to run an arbitrary command instead of killing the process
* #52 suggests an option for disabling the kill/replace cycle during updates

In any case, envconsul will need to support processes with a longer lifecycle in order to achieve this behavior. I think the above issues should cover this use case, so I'm closing this in favor of tracking them in the existing tickets.

Let me know if I missed anything!
